### PR TITLE
Add feature 'bundled' as a way to provide nanomsg as part of the cargo build.

### PR DESCRIPTION
**Pull request by photex**
I bumped the package versions up to 0.7 as well. 

This shouldn't break or change the default behavior that was previously used but if it does then I'm happy to figure out why and update the PR.

### CODE REVIEW

**Comment by photex** [comment]
There was some whitespace trimmage in the latest commit.. I can try and revert those if it's annoying/offensive. They just happen automatically for me.

**Comment by blabaere** [comment]
Removing the trailing spaces, or any other style oddities is absolutely fine. 
I'll try to investigate the travis build failure before merging the PR.
I'll be away from any computer for the rest of the week starting tomorrow so don't worry if you don't get any news in the meantime. 

Anyway, thanks a lot !!!

**Comment by photex** [comment]
Np. Enjoy the break!

**Comment by blabaere** [comment]
In [build.rs:24](https://github.com/photex/nanomsg.rs/blob/master/nanomsg_sys/build.rs#L24) the `NN_STATIC_LIB` compilation flags is set, but in [lib.rs:172](https://github.com/photex/nanomsg.rs/blob/master/nanomsg_sys/src/lib.rs#L172) the link type is unspecified, so it is to `dynamic`.
And in the Travis Makefile, it looks like `cmake install` requires sudo.

**Comment by blabaere** [comment]
@photex Got it this time ! The problem was a missing step in the Makefile used to build libnanomsg.
Please check the [file content in my fork](https://github.com/blabaere/nanomsg.rs/blob/master/Makefile) and update you PR accordingly. I'll merge it when I'll be back.

**Comment by photex** [comment]
heyo @blabaere !

My apologies for not getting to update my PR in-time to include your fixes.

**Pull request merged**
