### PR TITLE
check os for linux to skip ENOTSUP

### PR DESCRIPTION
**Pull request by ksaritek**
commited issue 

can not build at debian #163

### CODE REVIEW

**Comment by blabaere** [comment]
The Travis build failure looks related to a to how the tests are dealing with timeout but the AppVeyor build failure is really strange. I'll try to have a closer look.

**Comment by ksaritek** [comment]
Ok, by the way for now we use forked nanomsg at linux because of issue that I commited. When you have a look, we will put official dependency for nanomsg at toml.

**Comment by blabaere** [comment]
I will merge a PR that fixes this problem and upgrades to the latest libc.
By the way, the failing test on travis is not related to a timeout but seems very much like a real bug in how the subscribe socket option is implemented. I will file an issue for that later.

**Comment by blabaere** [comment]
Fixed with #165

**Pull request closed without merging**
