### PR TITLE
Change 2 booleans to 1 enum

### PR DESCRIPTION
**Pull request by pwoolcoc**
Since `socket.new_pollfd(false, false)` is not a particularly useful state
to be in, change this API to use an enum instead of 2 booleans. This allows
us to limit the API to only the states that are actually useful

### CODE REVIEW

**Comment by blabaere** [comment]
@pwoolcoc The changes look good to me but both Travis and my own machine are telling that the latest rust nightly package have wreaked havoc on cargo. Testing with rustc 1.0.0-nightly (c4fe7d6ae 2015-02-23) (built 2015-02-24). Will check again later.

**Comment by thehydroimpulse** [comment]
I believe the last nightly broke cargo or something according to the PSA on reddit.

**Comment by pwoolcoc** [comment]
Yea, I had to revert to 2015-02-22 to get cargo to work properly

**Comment by pwoolcoc** [comment]
I checked the travis build this morning, and it reminded me that I had forgotten to fix the tests :-/. So, I just pushed a fix for those, along with one more docs fix.

**Comment by thehydroimpulse** [comment]
@pwoolcoc Awesome, thanks a lot!

**Comment by blabaere** [comment]
@pwoolcoc PR  #103 does not build with the latest rust nightly because it is based on a version of the master that did not build. You should fetch the changes from the master and push them on your repo. This should fix the build.

**Comment by pwoolcoc** [comment]
@blabaere all set!

**Comment by blabaere** [comment]
@thehydroimpulse I agree with Travis, we can safely merge PR #103. This would make the API more usable.

**Pull request merged**
